[package]
name = "teehee"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
thiserror = "1.0.57"

[profile.release]
codegen-units = 1
lto = "fat"

#[build]
#rustflags = "-C target-cpu=native"
