input_path: ../../../bsc2.3
output_path: ../../../website2
gh_username: divkov575
gh_repo_name: website2
slack_api_token: ''
queue:
- - 60c01307ec7bb9326c521ac39071556da08431d7
  - added open graph protocol support after much trial an error
