input_path: ../../../lpm1-arcade
output_path: ../../../website
gh_username: divkov575
gh_repo_name: website
slack_api_token: ''
queue:
- - 3e723ebfd4c153b1fbd450cad6519459baea5401
  - improved mobile compatability
